### ISSUE TITLE
dataset

### ISSUE THREAD

**Issue by codeyyr** [pat-jj/TagReal#3]
Can you provide the Wikipedia dataset with version "20220301. en" and the "./Volumes/pubmed_corpus_text. txt" file

**Comment by pat-jj** [comment]
Hi, for the wikipedia dataset, we can't provide it as it is too large. You can find it by googling "Wikipedia 20220301.en".
For "./Volumes/pubmed_corpus_text. txt", it is from the dataset provided by [CPL](https://github.com/INK-USC/CPL). They provide the [link](https://drive.google.com/file/d/1hCyPBjywpMuShRJCPKRjc7n2vHpxfetg/view?usp=sharing) to download the dataset.

**Comment by fantastic-413** [comment]
> Hi, for the wikipedia dataset, we can't provide it as it is too large. You can find it by googling "Wikipedia 20220301.en". For "./Volumes/pubmed_corpus_text. txt", it is from the dataset provided by [CPL](https://github.com/INK-USC/CPL). They provide the [link](https://drive.google.com/file/d/1hCyPBjywpMuShRJCPKRjc7n2vHpxfetg/view?usp=sharing) to download the dataset.

There is no "./Volumes/pubmed_corpus_text.txt" in the data set, how to get it？
![image](https://github.com/pat-jj/TagReal/assets/57306219/98cfc2aa-fa28-46d5-b43f-70cb4cd1df03)
